### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by markdeegan** [AutoStephen/FYP2019#1]
Thanks for that Stephen. 
Can you please upload your Arduino sketch to this repository?
Thanks.
Mark

**Comment by markdeegan** [comment]
Sorry.
I just spotted you had already done that.
Thanks.

**Comment by markdeegan** [comment]
Have you tested using GItHub to synchronise your files from your laptop to the cloud?
Mark.

**Comment by AutoStephen** [comment]
I am doing that right now, slowly getting my head around it all...

**Comment by markdeegan** [comment]
Nice one. I never said this was simple. This is outside the bounds of what you have probably covered on your programme so far.
